### ISSUE TITLE
大佬，单卡训练的时候有一个问题

### ISSUE THREAD

**Issue by End1ezs** [Kamino666/video-captioning-swin-transformer#12]
AttributeError: 'MMT4Caption' object has no attribute 'module'
不知道哪里的问题

**Comment by Kamino666** [comment]
把更详细一点的报错放出来吧

**Comment by End1ezs** [comment]
Traceback (most recent call last):
  File "train.py", line 315, in <module>
    mmt4caption_train(cfg_.data, args_)
  File "train.py", line 245, in mmt4caption_train
    val_loss = val_epoch(model, val_dataloader, mode=cfg['train']['task'], local_args=local_args)
  File "/home/endless/anaconda3/envs/pytorchtest/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "train.py", line 161, in val_epoch
    loss = model.module(v_feats, v_masks, captions)
  File "/home/endless/anaconda3/envs/pytorchtest/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1185, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'MMT4Caption' object has no attribute 'module'


问题是在一轮结束后出现的。

**Comment by Kamino666** [comment]
哦哦，单卡训练参数有没有设置成--gpu呢，--gpu是单卡训练，--multi_gpu是多卡的

**Comment by Kamino666** [comment]
尝试一下使用--multi_gpu，然后把显卡数设置为1

**Comment by End1ezs** [comment]
> 哦哦，单卡训练参数有没有设置成--gpu呢，--gpu是单卡训练，--multi_gpu是多卡的
感谢大佬的回复，
python train.py -c ./configs/caption-task_baseline_modal_clip4clip_config.json --gpu  大佬，我之前用的参数是这个
然后刚才用多卡试了一下， python train.py -c ./configs/caption-task_baseline_modal_clip4clip_config.json -ws 1 --multi_gpu
现在这样报错
Traceback (most recent call last):
  File "train.py", line 305, in <module>
    args_ = configure_hardware(args_)
  File "/home/endless/pythonProject/Video-Captioning-Transformer-master/utils.py", line 138, in configure_hardware
    local_rank = int(os.environ["LOCAL_RANK"])
  File "/home/endless/anaconda3/envs/pytorchtest/lib/python3.8/os.py", line 675, in __getitem__
    raise KeyError(key) from None
KeyError: 'LOCAL_RANK'

**Comment by Kamino666** [comment]
用这个命令试一下
python -m torch.distributed.run --nproc_per_node 1 train.py -c ./configs/caption-task_baseline_modal_clip4clip_config.json --multi_gpu -ws 1

**Comment by End1ezs** [comment]
感谢大佬。

**Comment by greenhead01** [comment]
> 感谢大佬。
大佬，你使用完这个：
用这个命令试一下
python -m torch.distributed.run --nproc_per_node 1 train.py -c ./configs/caption-task_baseline_modal_clip4clip_config.json --multi_gpu -ws 1

有没有出现下面这个问题
(demo) D:\video_caption\Video-Captioning-Transformer>python -m torch.distributed.run --nproc_per_node 1 train.py -c ./clip4clip_msvd_config.json -ws 1            
W0319 09:43:32.289588 28136 site-packages\torch\distributed\elastic\multiprocessing\redirects.py:29] NOTE: Redirects are currently not supported in Windows or MacOs.
Traceback (most recent call last):
  File "D:\myconda\envs\demo\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\myconda\envs\demo\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\myconda\envs\demo\lib\site-packages\torch\distributed\run.py", line 922, in <module>
    main()
  File "D:\myconda\envs\demo\lib\site-packages\torch\distributed\elastic\multiprocessing\errors\__init__.py", line 355, in wrapper
    return f(*args, **kwargs)
  File "D:\myconda\envs\demo\lib\site-packages\torch\distributed\run.py", line 918, in main
    run(args)
  File "D:\myconda\envs\demo\lib\site-packages\torch\distributed\run.py", line 909, in run
    elastic_launch(
  File "D:\myconda\envs\demo\lib\site-packages\torch\distributed\launcher\api.py", line 138, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "D:\myconda\envs\demo\lib\site-packages\torch\distributed\launcher\api.py", line 260, in launch_agent
    result = agent.run()
  File "D:\myconda\envs\demo\lib\site-packages\torch\distributed\elastic\metrics\api.py", line 137, in wrapper
    result = f(*args, **kwargs)
  File "D:\myconda\envs\demo\lib\site-packages\torch\distributed\elastic\agent\server\api.py", line 711, in run
    result = self._invoke_run(role)
  File "D:\myconda\envs\demo\lib\site-packages\torch\distributed\elastic\agent\server\api.py", line 864, in _invoke_run
    self._initialize_workers(self._worker_group)
  File "D:\myconda\envs\demo\lib\site-packages\torch\distributed\elastic\metrics\api.py", line 137, in wrapper
    result = f(*args, **kwargs)
  File "D:\myconda\envs\demo\lib\site-packages\torch\distributed\elastic\agent\server\api.py", line 683, in _initialize_workers
    self._rendezvous(worker_group)
  File "D:\myconda\envs\demo\lib\site-packages\torch\distributed\elastic\metrics\api.py", line 137, in wrapper
    result = f(*args, **kwargs)
  File "D:\myconda\envs\demo\lib\site-packages\torch\distributed\elastic\agent\server\api.py", line 500, in _rendezvous
    rdzv_info = spec.rdzv_handler.next_rendezvous()
  File "D:\myconda\envs\demo\lib\site-packages\torch\distributed\elastic\rendezvous\static_tcp_rendezvous.py", line 67, in next_rendezvous
    self._store = TCPStore(  # type: ignore[call-arg]
RuntimeError: use_libuv was requested but PyTorch was build without libuv support

**Comment by Kamino666** [comment]
> > 感谢大佬。
> > 大佬，你使用完这个：
> > 用这个命令试一下
> > python -m torch.distributed.run --nproc_per_node 1 train.py -c ./configs/caption-task_baseline_modal_clip4clip_config.json --multi_gpu -ws 1
> 
> 有没有出现下面这个问题 (demo) D:\video_caption\Video-Captioning-Transformer>python -m torch.distributed.run --nproc_per_node 1 train.py -c ./clip4clip_msvd_config.json -ws 1 W0319 09:43:32.289588 28136 site-packages\torch\distributed\elastic\multiprocessing\redirects.py:29] NOTE: Redirects are currently not supported in Windows or MacOs. Traceback (most recent call last): File "D:\myconda\envs\demo\lib\runpy.py", line 197, in _run_module_as_main return _run_code(code, main_globals, None, File "D:\myconda\envs\demo\lib\runpy.py", line 87, in _run_code exec(code, run_globals) File "D:\myconda\envs\demo\lib\site-packages\torch\distributed\run.py", line 922, in main() File "D:\myconda\envs\demo\lib\site-packages\torch\distributed\elastic\multiprocessing\errors__init__.py", line 355, in wrapper return f(*args, **kwargs) File "D:\myconda\envs\demo\lib\site-packages\torch\distributed\run.py", line 918, in main run(args) File "D:\myconda\envs\demo\lib\site-packages\torch\distributed\run.py", line 909, in run elastic_launch( File "D:\myconda\envs\demo\lib\site-packages\torch\distributed\launcher\api.py", line 138, in **call** return launch_agent(self._config, self._entrypoint, list(args)) File "D:\myconda\envs\demo\lib\site-packages\torch\distributed\launcher\api.py", line 260, in launch_agent result = agent.run() File "D:\myconda\envs\demo\lib\site-packages\torch\distributed\elastic\metrics\api.py", line 137, in wrapper result = f(*args, **kwargs) File "D:\myconda\envs\demo\lib\site-packages\torch\distributed\elastic\agent\server\api.py", line 711, in run result = self._invoke_run(role) File "D:\myconda\envs\demo\lib\site-packages\torch\distributed\elastic\agent\server\api.py", line 864, in _invoke_run self._initialize_workers(self._worker_group) File "D:\myconda\envs\demo\lib\site-packages\torch\distributed\elastic\metrics\api.py", line 137, in wrapper result = f(*args, **kwargs) File "D:\myconda\envs\demo\lib\site-packages\torch\distributed\elastic\agent\server\api.py", line 683, in _initialize_workers self._rendezvous(worker_group) File "D:\myconda\envs\demo\lib\site-packages\torch\distributed\elastic\metrics\api.py", line 137, in wrapper result = f(*args, **kwargs) File "D:\myconda\envs\demo\lib\site-packages\torch\distributed\elastic\agent\server\api.py", line 500, in _rendezvous rdzv_info = spec.rdzv_handler.next_rendezvous() File "D:\myconda\envs\demo\lib\site-packages\torch\distributed\elastic\rendezvous\static_tcp_rendezvous.py", line 67, in next_rendezvous self._store = TCPStore( # type: ignore[call-arg] RuntimeError: use_libuv was requested but PyTorch was build without libuv support

看上去并不是关于这个repo的问题，猜测可能是pytorch安装上的问题。

**Comment by greenhead01** [comment]
> > > 感谢大佬。
> > > 大佬，你使用完这个：
> > > 用这个命令试一下
> > > python -m torch.distributed.run --nproc_per_node 1 train.py -c ./configs/caption-task_baseline_modal_clip4clip_config.json --multi_gpu -ws 1
> > 
> > 
> > 有没有出现下面这个问题 (demo) D:\video_caption\Video-Captioning-Transformer>python -m torch.distributed.run --nproc_per_node 1 train.py -c ./clip4clip_msvd_config.json -ws 1 W0319 09:43:32.289588 28136 site-packages\torch\distributed\elastic\multiprocessing\redirects.py:29] NOTE: Redirects are currently not supported in Windows or MacOs. Traceback (most recent call last): File "D:\myconda\envs\demo\lib\runpy.py", line 197, in _run_module_as_main return _run_code(code, main_globals, None, File "D:\myconda\envs\demo\lib\runpy.py", line 87, in _run_code exec(code, run_globals) File "D:\myconda\envs\demo\lib\site-packages\torch\distributed\run.py", line 922, in main() File "D:\myconda\envs\demo\lib\site-packages\torch\distributed\elastic\multiprocessing\errors__init__.py", line 355, in wrapper return f(*args, **kwargs) File "D:\myconda\envs\demo\lib\site-packages\torch\distributed\run.py", line 918, in main run(args) File "D:\myconda\envs\demo\lib\site-packages\torch\distributed\run.py", line 909, in run elastic_launch( File "D:\myconda\envs\demo\lib\site-packages\torch\distributed\launcher\api.py", line 138, in **call** return launch_agent(self._config, self._entrypoint, list(args)) File "D:\myconda\envs\demo\lib\site-packages\torch\distributed\launcher\api.py", line 260, in launch_agent result = agent.run() File "D:\myconda\envs\demo\lib\site-packages\torch\distributed\elastic\metrics\api.py", line 137, in wrapper result = f(*args, **kwargs) File "D:\myconda\envs\demo\lib\site-packages\torch\distributed\elastic\agent\server\api.py", line 711, in run result = self._invoke_run(role) File "D:\myconda\envs\demo\lib\site-packages\torch\distributed\elastic\agent\server\api.py", line 864, in _invoke_run self._initialize_workers(self._worker_group) File "D:\myconda\envs\demo\lib\site-packages\torch\distributed\elastic\metrics\api.py", line 137, in wrapper result = f(*args, **kwargs) File "D:\myconda\envs\demo\lib\site-packages\torch\distributed\elastic\agent\server\api.py", line 683, in _initialize_workers self._rendezvous(worker_group) File "D:\myconda\envs\demo\lib\site-packages\torch\distributed\elastic\metrics\api.py", line 137, in wrapper result = f(*args, **kwargs) File "D:\myconda\envs\demo\lib\site-packages\torch\distributed\elastic\agent\server\api.py", line 500, in _rendezvous rdzv_info = spec.rdzv_handler.next_rendezvous() File "D:\myconda\envs\demo\lib\site-packages\torch\distributed\elastic\rendezvous\static_tcp_rendezvous.py", line 67, in next_rendezvous self._store = TCPStore( # type: ignore[call-arg] RuntimeError: use_libuv was requested but PyTorch was build without libuv support
> 
> 看上去并不是关于这个repo的问题，猜测可能是pytorch安装上的问题。



> python -m torch.distributed.run --nproc_per_node 1 train.py -c ./configs/caption-task_baseline_modal_clip4clip_config.json --multi_gpu -ws 1
感谢回复， python -m torch.distributed.run --nproc_per_node 1 train.py -c ./configs/caption-task_baseline_modal_clip4clip_config.json --multi_gpu -ws 1 这条命令使用到的分布式训练吗？ 可能pytorch需要libuv来支持，这里的train.py使用的分布式训练吗？

**Comment by greenhead01** [comment]
大佬，这个项目是在windows开发的还是linux

**Comment by Kamino666** [comment]
Linux
