### ISSUE TITLE
缺少CLIP4CLIP-ViT-B-32模型

### ISSUE THREAD

**Issue by xieyuezhaoyuexie** [Kamino666/video-captioning-swin-transformer#13]
大佬，请问提取视频特征时是使用的CLIP4CLIP-ViT-B-32模型提取的特征吗？我在使用自己的视频生成字幕时，报错，缺少CLIP4CLIP-ViT-B-32.pth模型，请问大佬有这个模型吗？能发给我一份吗？

**Comment by Kamino666** [comment]
抱歉，CLIP4Clip微调后的模型未得到授权发布，可以尝试使用CLIP他们自带的预训练模型呢~

**Comment by xieyuezhaoyuexie** [comment]
好的，谢谢
