### ISSUE TITLE
How I can get the pre-trained model?

### ISSUE THREAD

**Issue by zydjohnHotmail** [Kamino666/video-captioning-swin-transformer#14]
Hello:
Please remember that due to the Internet blocking in China, anything published in Baidu, people outside China can't use.
Please consider to publish them in google.
Thanks,

**Comment by Kamino666** [comment]
Hello! I believe I did upload the model in Google Drive. Please check the tabular.

**Comment by zydjohnHotmail** [comment]
Hello:
Thanks, I got the model. 
How many langauges this model can use to produce video captioning? English and Chinese?

**Comment by Kamino666** [comment]
Only English for now. Because both the datasets do not support multi-language. I am planing to use another dataset(VATEX) but have difficulty downloading Youtube videos

**Comment by zydjohnHotmail** [comment]
Hello:
You can try this url to download  the dataset, but it may not work if you are in China.
But I am not sure if it is what you need.
https://www.kaggle.com/datasets/neverix/vatex-lowres/download

**Comment by Kamino666** [comment]
Thank you for the link! It is what I am looking for. I didn't know it is available in Kaggle. I will try it later.

**Comment by zydjohnHotmail** [comment]
You are welcome.
If you can make Chinese subtitle, let me know!
