### ISSUE TITLE
ModuleNotFoundError: No module named 'clip'

### ISSUE THREAD

**Issue by misayllk** [Kamino666/video-captioning-swin-transformer#17]
博主你好，我在运行过程中出错，缺少clip包。。。。
我尝试使用pip install clip但是失败了，我于是直接下载了clip原项目文件，放入了TextEncoder.py同一目录下，但仍无济于事，位置估计是放错了
（单gpu）
![image](https://user-images.githubusercontent.com/117498947/203303449-9a9ac386-238b-472a-abda-961dfa275549.png)

![image](https://user-images.githubusercontent.com/117498947/203303372-b5bfd2c3-3e6a-442c-8654-7fd833adf7ce.png)
![image](https://user-images.githubusercontent.com/117498947/203303400-958828f2-0246-4b0a-ab27-cdf58f05554d.png)
还望不吝赐教

**Comment by Kamino666** [comment]
问题解决了吗，clip的安装方式参考官方的repo哦https://github.com/openai/CLIP

**Comment by misayllk** [comment]
哈哈哈哈，等来了你的回复，解决了，但出现了新的问题，我是windows单卡训练，报了错，目前根据你提供的单卡训练报错解决方法在windows无法进行，正在尝试换linux试一下
万分感谢！！！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年11月23日(星期三) 下午5:21
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [Kamino666/Video-Captioning-Transformer] ModuleNotFoundError: No module named &#39;clip&#39; (Issue #17)





 
问题解决了吗，clip的安装方式参考官方的repo哦https://github.com/openai/CLIP

**Comment by Kamino666** [comment]
年代有些久远有些忘了windows行不行了，我之前都是在linux下跑的。
这个clip在训练阶段应该是可以不需要的，我代码可能没太写好orz
我后面对代码改进了但是还没弄完，过一段时间空闲下来可能会更新，更新之后就很方便用了hhhh

**Comment by misayllk** [comment]
辛苦大佬了！
行，我再做进一步尝试




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年11月23日(星期三) 下午5:38
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [Kamino666/Video-Captioning-Transformer] ModuleNotFoundError: No module named &#39;clip&#39; (Issue #17)





 
年代有些久远有些忘了windows行不行了，我之前都是在linux下跑的。
 这个clip在训练阶段应该是可以不需要的，我代码可能没太写好orz
 我后面对代码改进了但是还没弄完，过一段时间空闲下来可能会更新，更新之后就很方便用了hhhh
