### ISSUE TITLE
Hi！特征提取没在 GPU 上跑

### ISSUE THREAD

**Issue by XZJIsme** [Kamino666/video-captioning-swin-transformer#3]
![image](https://user-images.githubusercontent.com/30148847/141648764-06bc77a1-46a2-4e63-b8de-69cd48824da0.png)
之前就奇怪在不同性能的设备上跑效果都差不多，于是猜测其实在 CPU 上跑的，于是我指定了用 GPU 跑后快多了（`device=torch.device('cuda:0')`）
可能原项目（ https://github.com/v-iashin/video_features/tree/bmt ）就没处理好这个问题 😂

**Comment by Kamino666** [comment]
诶？！我看看，我之前用这个库提特征提的挺快的就没注意这一点了

**Comment by Kamino666** [comment]
应该不会出现device是cpu这种情况的啊
假如是单独用那个库的话，如图在main.py里用这几行代码就保证是GPU了，可能你没有指定device_id？

![](https://kamino-img.oss-cn-beijing.aliyuncs.com/20211114145724.png)

假如是从test_video.py里调用那个库的话，也保证了是GPU的，看看是不是少了`--gpu`这个参数呢 (ﾉ*ﾟｰﾟ)ﾉ

**Comment by XZJIsme** [comment]
> 应该不会出现device是cpu这种情况的啊 假如是单独用那个库的话，如图在main.py里用这几行代码就保证是GPU了，可能你没有指定device_id？
> 
> ![](https://camo.githubusercontent.com/3fd49b9a49e4ddd50f946fa75557d9ddb76bc0ec7b24d7d36db263e4386d16a1/68747470733a2f2f6b616d696e6f2d696d672e6f73732d636e2d6265696a696e672e616c6979756e63732e636f6d2f32303231313131343134353732342e706e67)
> 
> 假如是从test_video.py里调用那个库的话，也保证了是GPU的，看看是不是少了`--gpu`这个参数呢 (ﾉ*ﾟｰﾟ)ﾉ

设置了 gpu=True，不过没有专门设置 device_id

**Comment by XZJIsme** [comment]
> 设置了 gpu=True，不过没有专门设置 device_id

我明白了，设置了 gpu=True，也设置了 device_id，是我自己改错了代码，把此处的 id 改为了 1，应该是 0 才对！
![image](https://user-images.githubusercontent.com/30148847/142567038-88865a48-a66c-4f85-8c45-990ec9fc6882.png)
