### ISSUE TITLE
您好！最近在学习您的代码，被下面这个bug卡了好久了，请问能够帮忙看一下是啥问题呢？万分感谢！！

### ISSUE THREAD

**Issue by Akiraxty** [Kamino666/video-captioning-swin-transformer#4]
![image](https://user-images.githubusercontent.com/33471257/143513457-51ef3ffe-dee6-46a8-b934-ca3964f8df75.png)

**Comment by Kamino666** [comment]
挠头，我也感觉没啥问题呀，transformer的decoder的输入就应该是红框里这种shape的

有没有可能是pytorch版本问题呢，假如他说attn_mask的形状不对那就可能是Transformer的batch_first=True失效了？
https://pytorch.org/docs/stable/generated/torch.nn.Transformer.html#torch.nn.Transformer
