### ISSUE TITLE
用您的训练好的模型好像效果不好，请问您的模型的训练集多大

### ISSUE THREAD

**Issue by WindSearcher** [Kamino666/video-captioning-swin-transformer#5]

**Comment by Kamino666** [comment]
训练集是MSR-VTT的训练集，有6513个视频，验证集有497个视频

**Comment by WindSearcher** [comment]
好像还没SVT2架构好




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kamino666/Video-Captioning-Transformer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月30日(星期二) 上午9:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Kamino666/Video-Captioning-Transformer] 用您的训练好的模型好像效果不好，请问您的模型的训练集多大 (Issue #5)





 
训练集是MSR-VTT的训练集，有6513个视频，验证集有497个视频
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Kamino666** [comment]
hh可能哪里出问题了吧，我这边弄出来在所有指标上都挺好的呢

**Comment by WindSearcher** [comment]
我们的数据集是一条视频对应五个描述语句，不知道您的模型能做嘛




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kamino666/Video-Captioning-Transformer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月30日(星期二) 上午9:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Kamino666/Video-Captioning-Transformer] 用您的训练好的模型好像效果不好，请问您的模型的训练集多大 (Issue #5)





 
hh可能哪里出问题了吧，我这边弄出来在所有指标上都挺好的呢
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Kamino666** [comment]
是Video Captioning任务就可以用呀，像VATEX数据集、MSVD数据集都是这样的。假如你的数据集更小，可以试试迁移学习

**Comment by WindSearcher** [comment]
麻烦再问下，您用自己的tokenizer，而不用bert-base-uncase是基于啥考虑嘛？您的分词器是基于自己的训练集文本训练得到的嘛




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kamino666/Video-Captioning-Transformer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月30日(星期二) 上午9:27
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Kamino666/Video-Captioning-Transformer] 用您的训练好的模型好像效果不好，请问您的模型的训练集多大 (Issue #5)





 
是Video Captioning任务就可以用呀，像VATEX数据集、MSVD数据集都是这样的。假如你的数据集更小，可以试试迁移学习
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Kamino666** [comment]
我用的就是bert-base-uncase的tokenizer，之前因为网络原因下载到了本地，现在这个库最新的版本我应该是都替换成了能够直接下载hugging face的tokenizer文件的。可能你clone的还是上一个版本？

**Comment by WindSearcher** [comment]
嗷嗷，好的，谢谢，我自己手动换了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kamino666/Video-Captioning-Transformer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月30日(星期二) 上午10:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Kamino666/Video-Captioning-Transformer] 用您的训练好的模型好像效果不好，请问您的模型的训练集多大 (Issue #5)





 
我用的就是bert-base-uncase的tokenizer，之前因为网络原因下载到了本地，现在这个库最新的版本我应该是都替换成了能够直接下载hugging face的tokenizer文件的。可能你clone的还是上一个版本？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by WindSearcher** [comment]
麻烦再问下，这个视频得转成npy格式嘛？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kamino666/Video-Captioning-Transformer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月30日(星期二) 上午10:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Kamino666/Video-Captioning-Transformer] 用您的训练好的模型好像效果不好，请问您的模型的训练集多大 (Issue #5)





 
我用的就是bert-base-uncase的tokenizer，之前因为网络原因下载到了本地，现在这个库最新的版本我应该是都替换成了能够直接下载hugging face的tokenizer文件的。可能你clone的还是上一个版本？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by WindSearcher** [comment]
Traceback (most recent call last):
&nbsp; File "train.py", line 330, in <module&gt;
&nbsp; &nbsp; train_loss = train_epoch(transformer, optimizer, train_dataloader)
&nbsp; File "train.py", line 75, in train_epoch
&nbsp; &nbsp; src_mask=None, src_padding_mask=src_padding_mask)&nbsp; # N T-1 vocab_szie
&nbsp; File "/home/mmifhost/miniconda3/envs/pytorchenv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
&nbsp; &nbsp; return forward_call(*input, **kwargs)
&nbsp; File "/home/lab-space/personal/lq/code/Video-Captioning-Transformer-master/model/model.py", line 58, in forward
&nbsp; &nbsp; src_emb = self.positional_encoding(self.src_to_emb(src))&nbsp; # src: torch.Size([16, 768, 20])
&nbsp; File "/home/mmifhost/miniconda3/envs/pytorchenv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
&nbsp; &nbsp; return forward_call(*input, **kwargs)
&nbsp; File "/home/mmifhost/miniconda3/envs/pytorchenv/lib/python3.7/site-packages/torch/nn/modules/linear.py", line 103, in forward
&nbsp; &nbsp; return F.linear(input, self.weight, self.bias)
&nbsp; File "/home/mmifhost/miniconda3/envs/pytorchenv/lib/python3.7/site-packages/torch/nn/functional.py", line 1848, in linear
&nbsp; &nbsp; return torch._C._nn.linear(input, weight, bias)
RuntimeError: mat1 and mat2 shapes cannot be multiplied (2560x2048 and 512x768)

您好，换成我的数据集后报这种错，请问是否是把hidden_dim维度换成512?




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kamino666/Video-Captioning-Transformer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月30日(星期二) 上午10:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Kamino666/Video-Captioning-Transformer] 用您的训练好的模型好像效果不好，请问您的模型的训练集多大 (Issue #5)





 
我用的就是bert-base-uncase的tokenizer，之前因为网络原因下载到了本地，现在这个库最新的版本我应该是都替换成了能够直接下载hugging face的tokenizer文件的。可能你clone的还是上一个版本？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Kamino666** [comment]
hidden_dim可以改呀
这个报错应该是2048这个维度弄错了，检查一下输入

**Comment by WindSearcher** [comment]
应该是我当时抽取的视频特征npy文件不对，所以用大佬提供的CLIP来重新抽取，就发生了上一封邮件存在的问题




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kamino666/Video-Captioning-Transformer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月30日(星期二) 下午2:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Kamino666/Video-Captioning-Transformer] 用您的训练好的模型好像效果不好，请问您的模型的训练集多大 (Issue #5)





 
hidden_dim可以改呀
 这个报错应该是2048这个维度弄错了，检查一下输入
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
