### ISSUE TITLE
能说下特征提取的相关参数介绍嘛

### ISSUE THREAD

**Issue by WindSearcher** [Kamino666/video-captioning-swin-transformer#6]

**Comment by Kamino666** [comment]
README.md里面的数据准备中有写

**Comment by WindSearcher** [comment]
python main.py --feature_type CLIP-ViT-B/32 --video_dir /home/mmifhost/桌面/video-caption.pytorch/data/train-video --device_ids 0 --on_extraction save_numpy --extraction_fps 3 --stack_size 224 --step_size 224 --output_path /home/lab-space/personal/lq/code/Video-Captioning-Transformer/data


大佬，我没有看到CLIP提取特征参数为：抽帧fps3，resize为224*224，使用CLIP的CLIP-ViT-B/32版本中resize怎么在video-features这个项目里面咋配置，我运行这个项目报RuntimeError: stack expects a non-empty TensorList，但是能看到保存的npy文件，不知道大佬在抽取CILP特征有没有遇到




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kamino666/Video-Captioning-Transformer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月30日(星期二) 下午2:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Kamino666/Video-Captioning-Transformer] 能说下特征提取的相关参数介绍嘛 (Issue #6)





 
README.md里面的数据准备中有写
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Kamino666** [comment]
在video-features这个库里原作者有个文档，CLIP提取特征是我加上去的内容，可以借鉴文档和main.py里argparse的注释来用命令。那个库我准备在论文出来之后维护XD，所以现在可能得看看代码了

**Comment by WindSearcher** [comment]
嗯嗯，主要就是resize没看到这个参数，谢谢大佬




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Kamino666/Video-Captioning-Transformer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月30日(星期二) 下午2:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Kamino666/Video-Captioning-Transformer] 能说下特征提取的相关参数介绍嘛 (Issue #6)





 
在video-features这个库里原作者有个文档，CLIP提取特征是我加上去的内容，可以借鉴文档和main.py里argparse的注释来用命令。那个库我准备在论文出来之后维护XD，所以现在可能得看看代码了
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Kamino666** [comment]
好的，谢谢支持~
