### ISSUE TITLE
作者：更新预告

### ISSUE THREAD

**Issue by Kamino666** [Kamino666/video-captioning-swin-transformer#9]
这份代码已经进行了完全的重构，效果和功能也添加了很多，但是代码还没写完，学业上也比较忙，所以还要再等一段时间才能推上来，谢谢支持~

**Comment by HJXH** [comment]
您好，大佬，MSR-VTT的数据集能网盘发我一份吗 sdndhjx@163.com

**Comment by Kamino666** [comment]
您好！您的邮件我已收到！

**Comment by HJXH** [comment]
您好，大佬，新的版本有吗，还有您安装的transformers是什么版本的，我用的最新4.16.2版本报异常，原因是src和tgt后两个维度（length和dim）要求一样

**Comment by Kamino666** [comment]
您好！您的邮件我已收到！

**Comment by Kamino666** [comment]
> 您好，大佬，新的版本有吗，还有您安装的transformers是什么版本的，我用的最新4.16.2版本报异常，原因是src和tgt后两个维度（length和dim）要求一样

你好呀，现在更新了版本，假如还感兴趣可以试试新的代码！！

**Comment by HJXH** [comment]
你好，你模型得到的这几个指标是在测试集上评估的吗，看了下你的config文件用的都是验证集（val）,还是这个任务评估只需要用验证集就可以，对视频描述这个比较感兴趣，希望能得到大佬的回答











在 2022-03-11 11:15:56，"Kamino" ***@***.***> 写道：

您好，大佬，新的版本有吗，还有您安装的transformers是什么版本的，我用的最新4.16.2版本报异常，原因是src和tgt后两个维度（length和dim）要求一样

你好呀，现在更新了版本，假如还感兴趣可以试试新的代码！！

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Kamino666** [comment]
> 你好，你模型得到的这几个指标是在测试集上评估的吗，看了下你的config文件用的都是验证集（val）,还是这个任务评估只需要用验证集就可以，对视频描述这个比较感兴趣，希望能得到大佬的回答 在 2022-03-11 11:15:56，"Kamino" ***@***.***> 写道： 您好，大佬，新的版本有吗，还有您安装的transformers是什么版本的，我用的最新4.16.2版本报异常，原因是src和tgt后两个维度（length和dim）要求一样 你好呀，现在更新了版本，假如还感兴趣可以试试新的代码！！ — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: ***@***.***>

一直忽略了这个问题……
我这份MSR-VTT数据集的测试集没有标注，然后就一直用的验证集，过两天我补个测试集的结果吧

**Comment by Kamino666** [comment]
> 你好，你模型得到的这几个指标是在测试集上评估的吗，看了下你的config文件用的都是验证集（val）,还是这个任务评估只需要用验证集就可以，对视频描述这个比较感兴趣，希望能得到大佬的回答 在 2022-03-11 11:15:56，"Kamino" ***@***.***> 写道： 您好，大佬，新的版本有吗，还有您安装的transformers是什么版本的，我用的最新4.16.2版本报异常，原因是src和tgt后两个维度（length和dim）要求一样 你好呀，现在更新了版本，假如还感兴趣可以试试新的代码！！ — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: ***@***.***>

你好，我已经更新好了新的数据，假如还有问题可以单独发issue

**Comment by HJXH** [comment]
大佬，repo里您提供的的msr-vtt和msvd数据集的clip特征，参数设置是怎样的（比如 fps或者uni是多少），还有这种设置是经过试验验证了吗，还是随便设置的





At 2022-03-11 16:34:36, "Kamino" ***@***.***> wrote:

Closed #9.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Kamino666** [comment]
> 大佬，repo里您提供的的msr-vtt和msvd数据集的clip特征，参数设置是怎样的（比如 fps或者uni是多少），还有这种设置是经过试验验证了吗，还是随便设置的 At 2022-03-11 16:34:36, "Kamino" ***@***.***> wrote: Closed #9. — Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you commented.Message ID: ***@***.***>

CLIP4Clip中使用的是固定抽12帧，然后就沿用下来了
